### ISSUE TITLE
[FEATURE] 마이페이지 UI 구현

### ISSUE THREAD

**Issue by joohaem** [gql-study/SOPTstagram-frontend#1]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 마이페이지 UI 를 구현합니다

## TODO

- [ ] 마이페이지 헤더
- [ ] 유저 정보 섹션
- [x] ~스토리~
- [ ] 피드 섹션
