### ISSUE TITLE
[FEATURE] 게시글 작성뷰 컴포넌트 구조잡기

### ISSUE THREAD

**Issue by Nahee-Park** [gql-study/SOPTstagram-frontend#4]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 게시글 작성뷰 컴포넌트 구조를 잡아볼 거예요

## TODO

- [ ] 컴포넌트 구조 잡기
- [ ] UX 어떻게 가져갈 지 고민..하기
