### ISSUE TITLE
피드 퍼블리싱 완료하기

### ISSUE THREAD

**Issue by NamJwong** [gql-study/SOPTstagram-frontend#6]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 피드 퍼블리싱 완료하기

## TODO

- [ ] 피드 퍼블리싱 완료하기
